### ISSUE TITLE
Invalid token shouldn't crash the server

### ISSUE THREAD

**Issue by jankeromnes** [espadrine/email-login#3]
My server just crashed with this, because a user didn't submit a valid token:

```
/home/janx/janitor/node_modules/email-login/src/api.js:188
    token: tokenBase64url.replace(/\-/g, '+').replace(/_/g, '/'),
                         ^

TypeError: Cannot read property 'replace' of undefined
    at decodeToken (/home/janx/janitor/node_modules/email-login/src/api.js:188:26)
    at Object.Api.confirmEmail (/home/janx/janitor/node_modules/email-login/src/api.js:71:20)
    at /home/janx/janitor/lib/users.js:36:11
    at /home/janx/janitor/lib/users.js:129:7
    at /home/janx/janitor/node_modules/email-login/src/api.js:27:7
    at /home/janx/janitor/node_modules/email-login/src/registry.js:304:43
    at /home/janx/janitor/node_modules/email-login/src/registry.js:249:16
    at FSReqWrap.oncomplete (fs.js:82:15)
```

Maybe `decodeToken` should bail out or throw if `base64.split('.')` doesn't return 3 elements?

**Comment by espadrine** [comment]
Thanks for raising this issue. I will inspect similarly dangerous spots and add a patch tomorrow.

**Comment by jankeromnes** [comment]
:+1:

**Comment by jankeromnes** [comment]
Looks good, thanks!
